version: "0.0"
volumes:
  bitcoin-data:
  api_modules:
  client_modules:

services:
  bitcoind:
    image: bitcoind
    container_name: bitcoind
    volumes:
      - bitcoin-data:/data
      - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
    stdin_open: true
    tty: true
    ports:
      - "8332:8332"
      - "8333:8333"
    restart: always
  api:
    container_name: server
    image: lbtc_server
    environment:
      - NODE_ENV=$API_NODE_ENV
      - PORT=$API_PORT
      - MONGO_USER=$MONGO_USER
      - MONGO_PASS=$MONGO_PASS
      - PROD_TOKEN_SECRET
      - FAUCET_ADDRESS
      - RPC=$RPC
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - api_modules:/server/node_modules
    restart: always
  ui_build:
    image: ui_build
    volumes:
      - ./client/build:/app/build
      - client_modules:/app/node_modules
    container_name: client_build
    environment:
      - NODE_ENV=$UI_NODE_ENV
      - REACT_APP_API_HOST="http://localhost:5000"
    # ports:
    #   - $UI_PORT:$UI_PORT
    stdin_open: true
  ui_server:
    image: nginx:1.19.4-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client/build:/usr/share/nginx/html
