version: "0.0"
volumes:
  - bitcoin-data:
networks:
  - wallet
services:
  bitcoind:
    image: bitcoind
    container_name: bitcoind
    volumes:
      - bitcoin-data:/data
      - ./bitcoind/bitcoin.conf:/root/.bitcoin/bitcoin.conf
    networks:
      - bitcoin
    stdin_open: true
    tty: true
    ports:
      - "8332:8332"
      - "8333:8333"
  api:
    container_name: server
    image: lbtc_server
    environment:
      - NODE_ENV=$API_NODE_ENV
      - PORT=$API_PORT
      - MONGO_USER=$MONGO_USER
      - MONGO_PASS=$MONGO_PASS
      - RPC=$RPC
    ports:
      - $API_PORT:$API_PORT
  ui:
    image: lbtc_client
    container_name: client
    environment:
      - NODE_ENV=$UI_NODE_ENV
      - PORT=$UI_PORT
      - REACT_APP_API_HOST
    ports:
      - $UI_PORT:$UI_PORT
    stdin_open: true
